# Generated by Django 3.2 on 2021-05-27 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='picture',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='pictures/%y/%m/%d/'),
        ),
    ]
