# Generated by Django 3.2 on 2021-05-27 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_photo_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='id',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='photo_url',
        ),
        migrations.AddField(
            model_name='photo',
            name='photo_id',
            field=models.CharField(default='', max_length=5000, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='photo',
            name='picture',
            field=models.ImageField(blank=True, max_length=255, upload_to='pictures/%y/%m/%d/'),
        ),
    ]
