# Generated by Django 3.2.3 on 2021-07-09 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210709_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='mpesatransaction',
            name='user_phone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
