# Generated by Django 3.2.3 on 2021-07-09 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_mpesatransaction_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='mpesatransaction',
            name='request_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
