# Generated by Django 3.2 on 2021-06-01 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_user_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='Liked',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('who_liked', models.CharField(max_length=100)),
                ('whom_liked', models.CharField(max_length=100)),
            ],
        ),
    ]
