# Generated by Django 3.2 on 2021-06-01 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_liked'),
    ]

    operations = [
        migrations.AddField(
            model_name='liked',
            name='like_fav',
            field=models.CharField(default='None', max_length=50),
        ),
    ]
