# Generated by Django 3.2 on 2021-06-03 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_liked_like_fav'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('who_liked', models.CharField(max_length=100)),
                ('whom_liked', models.CharField(max_length=100)),
                ('exp', models.CharField(default='None', max_length=50)),
                ('whom_name', models.CharField(default='', max_length=50)),
                ('whom_work', models.CharField(default='', max_length=50)),
                ('profile_image', models.CharField(default='', max_length=1000)),
            ],
        ),
        migrations.DeleteModel(
            name='Liked',
        ),
    ]
