# Generated by Django 3.2 on 2021-06-06 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210603_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='is_id',
            field=models.BooleanField(default=False),
        ),
    ]
