# Generated by Django 3.2 on 2021-06-06 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_photo_is_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='is_id',
            field=models.CharField(default='false', max_length=10),
        ),
    ]
