# Generated by Django 3.2 on 2021-06-06 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_user_verification_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='expression',
            name='ver_status',
            field=models.CharField(default='Unverified', max_length=10),
        ),
    ]
