# Generated by Django 3.2 on 2021-06-07 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20210607_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='expression',
            name='who_work',
            field=models.CharField(default='', max_length=100),
        ),
    ]
