# Generated by Django 3.2.3 on 2021-06-25 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admincred',
            name='status',
            field=models.IntegerField(default=9),
        ),
    ]
