# Generated by Django 3.2.3 on 2021-06-26 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_reportedaccounts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reportedaccounts',
            old_name='user_address',
            new_name='user_email',
        ),
    ]
