# Generated by Django 3.2.3 on 2021-06-26 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0004_rename_user_address_reportedaccounts_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportedaccounts',
            name='user_image',
            field=models.CharField(max_length=1000),
        ),
    ]
