# Generated by Django 3.2.3 on 2021-06-26 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0005_alter_reportedaccounts_user_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaidUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_image', models.CharField(max_length=1000)),
                ('user_name', models.CharField(max_length=50)),
                ('user_email', models.CharField(max_length=50)),
            ],
        ),
    ]
